# Generated by Django 4.2.2 on 2023-06-25 00:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="general-user-User-id-label",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="general-user-User-first_name-label",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="general-user-User-last_name-label",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="general-user-User-email-label",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "general-user-User-label",
                "verbose_name_plural": "general-user-Users-label",
            },
        ),
    ]
